on:
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: schema check
        env:
          HIVE_TOKEN: ${{ secrets.HIVE_TOKEN }}
          HIVE_ENDPOINT: ${{ secrets.HIVE_ENDPOINT }}
        run: |
          npm i -g @graphql-hive/cli@latest
          hive schema:check "schema.graphql" \
            --registry.accessToken ${{ env.HIVE_TOKEN }} \
            --registry.endpoint ${{ env.HIVE_ENDPOINT }} \
            --service whatever \
            --github
